(in-package :mu-cl-resources)

(setf *include-count-in-paginated-responses* t)
(setf *supply-cache-headers-p* t)
(setf sparql:*experimental-no-application-graph-for-sudo-select-queries* t)
(setf *cache-model-properties-p* t)
(setf mu-support::*use-custom-boolean-type-p* nil)
(setq *cache-count-queries-p* t)
(setf sparql:*query-log-types* nil)

(define-resource message ()
  :class (s-prefix "ext:Message")
  :properties `((:sender :string ,(s-prefix "ext:sender"))
                (:content :string ,(s-prefix "ext:content"))
                (:sent-at :datetime ,(s-prefix "ext:sentAt")))
  :resource-base (s-url "http://mu.semte.ch/messages/")
  :on-path "messages")

(define-resource task ()
  :class (s-prefix "ext:Task")
  :properties `((:title :string ,(s-prefix "dct:title"))
                (:status :string ,(s-prefix "ext:status")))
  :features '(include-uri)
  :resource-base (s-url "http://mu.semte.ch/tasks/")
  :on-path "tasks")

(read-domain-file "domain.json")
